# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - actionstest2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://bigdatameeting.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_493eac0ec64b4a65b1ac8bf3971c6cdc }}
          password: ${{ secrets.AzureAppService_ContainerPassword_206b2e30cf1f40a2a69a907b5a5f6cc2 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: bigdatameeting.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_493eac0ec64b4a65b1ac8bf3971c6cdc }}/actiontest2:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'actionstest2'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_813f00edc3f343fb8b760ea3003a5b41 }}
            images: 'bigdatameeting.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_493eac0ec64b4a65b1ac8bf3971c6cdc }}/actiontest2:${{ github.sha }}'
